# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch: false
  branches:
    include:
    - master

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
    - master

strategy:
  # Limit number of executors used so other pipelines can run too
  maxParallel: 10
  matrix:
    mac-ghc-master-9.6.3:
      image: "macOS-latest"
      mode: "--ghc-flavor ghc-master"
      resolver: "ghc-9.6.3"
      stack-yaml: "stack-exact.yaml"

pool: {vmImage: '$(image)'}

steps:
  # macOS
  - bash: |
      set -euxo pipefail
      CXX="/usr/bin/g++ -std=gnu++11"
      if ! "$CXX" -E actest.cpp -o actest.out; then
        echo "Failed to compile test program"
        cat actest.out
      fi
    condition: eq( variables['Agent.OS'], 'Darwin' )
    displayName: Install brew
